### ISSUE TITLE
Code annotations fail to render with `techdocs-core` plugin enabled

### ISSUE THREAD

**Issue by rmartine-ias** [backstage/mkdocs-techdocs-core#128]
Something `techdocs-core` is doing (maybe [setting](https://github.com/backstage/mkdocs-techdocs-core/commit/ec5dcc17c917a383f8b43e3ce11484c17491bcfd) `theme.palette` to `''`?) prevents [code annotations](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-annotations) from rendering.

Reproduction:
```shell
python3.11 -m venv .venv
source .venv/bin/activate
pip install mkdocs-techdocs-core
mkdir docs
```

`mkdocs.yml`:

```yaml
site_name: Backstage Docs
theme:
  name: material
  features:
    - content.code.annotate
nav:
  - Home: index.md
markdown_extensions:
  - pymdownx.superfences
```

`docs/index.md`:

    ```yaml
    # (1)
    ```

    1. An annotation

```shell
mkdocs build
open site/index.html # You should see a clickable annotation
yq -i '.plugins[0] = "techdocs-core"' mkdocs.yml
mkdocs build
open site/index.html # You should not see an annotation
```

Without techdocs:
<img width="487" alt="Screenshot 2023-06-08 at 3 54 20 PM" src="https://github.com/backstage/mkdocs-techdocs-core/assets/107639398/6f0fa328-fc3d-4f62-bdf7-3891b7067dd0">

With it:
<img width="164" alt="Screenshot 2023-06-08 at 3 54 24 PM" src="https://github.com/backstage/mkdocs-techdocs-core/assets/107639398/4f8d7e23-0b3a-47cc-9dc3-4ac1da8763f6">

I noticed that if I have no plugins set, and set `theme.palette` to `""`, then annotations also fail to render. So I think this might be causing it, but don't see an easy fix.

**Comment by steven-terrana-bah** [comment]
I came to the same conclusion that this issue was being caused by `theme.palette: ""` so i tried creating a hook that overrides this value _after_ the `techdocs-core` plugin makes its configuration changes (just to see what would happen).

This fixed code annotation rendering on the mkdocs site directly (`http://localhost:8000`) but **not** in the techdocs rendering within backstage (`http://localhost:3000`) when running `techdocs-cli serve`.

**mkdocs.yml**
``` yaml
site_name: test-annotations

theme:
  name: material
  features:
    - content.code.annotate  
  palette.scheme: default

plugins: 
 - techdocs-core

hooks:
- hooks.py

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - home: index.md
```

**hook.py**
``` py
import mkdocs

@mkdocs.plugins.event_priority(-100)
def on_config(config):
    config['theme']['palette'] = {}
    config['theme']['palette']['scheme'] = 'default'
    return config
```
