### ISSUE TITLE
configuration options for plantuml_markdown

### ISSUE THREAD

**Issue by hpgrahsl** [backstage/mkdocs-techdocs-core#169]
Hi all,

according to the readme the [plantuml_markdown](https://pypi.org/project/plantuml-markdown/) extension is part of techdocs core. What's unclear to me is how I could provide configuration for this extension when running techdocs-cli to locally process some documentation?

e.g. where would I specify that I want to use a remote plantuml server to render instead of doing it locally by means of the plantuml.jar ?

Thanks for any pointers.

**Comment by hpgrahsl** [comment]
I eventually figured this out earlier today. The part that isn't easy to find is that the mkdocs conf needs to look as follows:

```yaml
...
markdown_extensions: 
  - plantuml_markdown:
      option1: ...
      ...
      optionN: ...
...
```
