### ISSUE TITLE
Changing admonition icon set not working

### ISSUE THREAD

**Issue by 5nafu** [backstage/mkdocs-techdocs-core#172]
We are currently trying to change the admonition icons as explained in the [material theme documentation](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#admonition-icons).

Our mkdocs.yaml looks like this:
```yaml
site_name: '...'
site_description: '...'
#uncomment the below lines if you want to enable the edit button in your techdocs
edit_uri: blob/main/docs/ #don't change it, just uncomment
repo_url: '...'
theme:
  name: material
  palette:
    scheme: default
  features:
    - toc.follow
    - navigation.indexes
    - content.code.copy
    - content.code.annotate
  icon:
    admonition:
      example: fontawesome/solid/flask
plugins:
  - techdocs-core
  - awesome-pages
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - mdx_truly_sane_lists:
      nested_indent: 4
```

Unfortunately, the icons stay the same when we try to run a preview of the documentation with `npx @techdocs/cli serve`. If we switch to mkdocs (`mkdocs serve`) directly, the icons work as expected.

We found an issue squidfunk/mkdocs-material#3987 suggesting that removing the `palette` setting might solve the issue, but this did not help in out case.
