### ISSUE TITLE
Support for Category-Specific Sidebars to Reduce Artifact Size in MkDocs Monorepo Plugin

### ISSUE THREAD

**Issue by RaizadaHaroon** [backstage/mkdocs-techdocs-core#201]
We are managing documentation for around 100 products in a single repository using the MkDocs Monorepo Plugin. The root mkdocs.yml file utilizes !include to include configuration files for each product.

## Current Structure:

```
mkdocs.yml
products/
    prod1/
        mkdocs.yml
        docs/
            index.md
            topic1.md
            topic2.md
    prod2/
        mkdocs.yml
        docs/
            index.md
            topic1.md
            topic2.md
    # and so on for 100 products
docs/
    index.md

```

Root mkdocs.yml Configuration:

```
site_name: 'Main Documentation Site'
nav:
  - Home: index.md
  - Products:
      !include: 'products/prod1/mkdocs.yml'
      !include: 'products/prod2/mkdocs.yml'
      # Add more products as needed
plugins:
  - search
  - monorepo

```

## Concern:

Currently, each rendered HTML page includes the sidebar tree for all 100 products, which significantly increases the artifact size. This is inefficient and can negatively impact the performance and usability of our documentation site.
