### ISSUE TITLE
Cannot override config of extensions appended in techdocs-core

### ISSUE THREAD

**Issue by kunickiaj** [backstage/mkdocs-techdocs-core#220]
For example, if one wants to enable slugify on content tabs, they cant because the extension is always appended even if already configured in the user's mkdocs.yml

I saw https://github.com/backstage/mkdocs-techdocs-core/pull/214 which i think intended to address this issue, but i still cant get configuration to get merged with the default atechdocs one.

https://github.com/backstage/mkdocs-techdocs-core/blob/8bc1e2a79dc56f160458f6a8ab65393277a01456/src/core.py#L127

Have also tried

```yaml
plugins:
  - techdocs-core
markdown_extensions:
  - pymdownx.extra:
      pymdownx.tabbed:
        slugify: !!python/object/apply:pymdownx.slugs.slugify
          kwds:
            case: lower
```

I suspect the issue is that while #214 removed the superfences plugin from the list of appended, it did not remove the others provided by `pymdownx.extra` still resulting in impossible configuration for those.
