### ISSUE TITLE
Techdocs not being build on Backstage throwing 404 error

### ISSUE THREAD

**Issue by rgcouto** [backstage/mkdocs-techdocs-core#269]
Hello!

### Summary

I'm opening here an issue because I don't know anymore what to do in order to fix this issue I'm experiencing. In a nutshell, I have a repository on Gitlab with a MKDocs config file that builds successfully the techdocs site when I use the `techdocs-cli` CLI but then on Backstage when I include the catalog entry I get a (somewhat) random error about Failing to read from Gitlab. I'm using the same setup on a different repository and it works really good there, it's just this one that is failling. 

Let me detail my issue below.

### My Configuration

This is my Backstage `app-config.yaml` config:
```yaml
...
techdocs:
  builder: 'local'
  generator:
    runIn: 'local'
  publisher:
    type: 'local'
...
```

The `catalog-info.yaml` file is within the `.gitlab/` directory and the `mkdocs.yml` file is in the root of the repo:
```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
    name: my-repo-with-docs
    description: The repo with the docs
    annotations:
      gitlab.com/project-id: '0123456789'
      backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name==my-repo-with-docs'
      backstage.io/source-location: url:https://gitlab.com/myorg/my-repo-with-docs
      backstage.io/techdocs-ref: dir:../ # have to go up one dir because we're in .gitlab/
      sonarqube.org/project-key: myorg_my-repo-with-docs
....
```

The `mkdocs.yml`  file looks like this:
```yaml
site_name: the-docs-of-the-repo
site_description: The docs of the repo
repo_url: https://gitlab.com/myorg/my-repo-with-docs
repo_name: my-repo-with-docs

nav:
  - Home: index.md
  - Local Development Guide:
    - Auth0 Setup for Local Development: Auth0Setup.md
  - App configuration (appsettings.json):
    - OpenID Connect: OpenIdConnect.md
    - User Groups: UserGroups.md
  ... # more nav entries

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.expand
    - search.highlight
  palette:
    scheme: slate
    primary: blue grey
    accent: indigo

plugins:
  - techdocs-core
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true
```

This is my repo file structure
```
.gitlab/
 | - catalog-info.yaml
 | - ...
docs/
 | - index.md
 | - Auth0Setup.md
 | - OpenIdConnect.md
 | - UserGroups.md
 | - ...
mkdocs.yml
...
```

### What I do to have it working
When running it locally on my computer everything works fine:
- `techdocs-cli generate --no-docker` doesn't throw any error and generates the `site/` directory with the documentation;
- `techdocs-cli serve` also doesn't throw any errors and opens the browser with the documentation in Backstage's template just as expected.

### What happens when using Backstage and Gitlab
- I add the `catalog-info.yaml` to our Backstage platform, it doesn't throw any exceptions, so I'm guessing everything this is ok;
- I navigate to the Docs menu and click o the `my-repo-with-docs` entry and it shows an error page:
  - Some of the messages shown in the screen are:
    - Building a newer version of this documentation failed. Error: "Failed to read tree from https://gitlab.com/myorg/, 404 Not Found"
    - ERROR 404: NotFoundError: Page not found. This could be because there is no index.md file in the root of the docs directory of this repository.
  - These are the `Build Details` output:
    - info: Step 1 of 3: Preparing docs for entity component:default/my-repo-with-docs {"timestamp":"2025-04-09T08:25:14.688Z"}
    - error: Failed to build the docs page for entity component:default/my-repo-with-docs: Failed to read tree from https://gitlab.com/myorg/

**REMARKS: Obviously that `myorg` and `my-repo-with-docs` are not a real names but rather generic names I gave for privacy reasons**

Thank you for your help in advance.
