### ISSUE TITLE
bug: not working with markdown_extensions : md_in_html

### ISSUE THREAD

**Issue by kim5566** [backstage/mkdocs-techdocs-core#39]
# Bug: Should remove trailing whitespace in HTML tags.
```yaml
site_name: test

nav:
  - 'index.md'

plugins:
  - techdocs-core
markdown_extensions:
  - md_in_html
```
I have markdown content inside HTML tag. 
For example, the following:
```
<div markdown="1">

This is a *Markdown* Paragraph.

</div>
```
...is rendered as:
```
<div>
<p>This is a <em>Markdown</em> Paragraph.</p>
</div>
```
### However, it breaks when there's trailing whitespace
For example, the following:
```
<div markdown = "1">

This is a *Markdown* Paragraph.

</div>
```
...is rendered as:
```
<div>
<p>= "1"&gt;</p>
<p>This is a <em>Markdown</em> Paragraph.</p>
</div>
```
# Expected behavior: 

Should be rendered as:
```
<div>
<p>This is a <em>Markdown</em> Paragraph.</p>
</div>
```

# Context:
techdocs-cli --version 0.7.0

# Note
This seems not to be a bug of mkdocs. If I run `mkdocs:serve` (version 1.2.2), I get the expected behaviour. 
Only happens if I run `techdocs-cli serve:mkdocs`
