### ISSUE TITLE
techdocs-core breaks livereload

### ISSUE THREAD

**Issue by RmMsr** [backstage/mkdocs-techdocs-core#40]
Hei,

I am not able to run mkdocs through techdocs-cli. It works if I directly run `mkdocs serve --no-livereload` or if I comment out the `techdocs-core` plugin. So I assume the plugin somehow breaks the livereload.

This is the error:

```
techdocs-cli serve --verbose --no-docker
info: Starting mkdocs server.
verbose: [mkdocs] INFO     -  Building documentation...
verbose: [mkdocs] INFO     -  Cleaning site directory
verbose: [mkdocs] INFO     -  Documentation built in 0.32 seconds
verbose: [mkdocs] Traceback (most recent call last):
verbose: [mkdocs]   File "/usr/bin/mkdocs", line 33, in <module>
verbose: [mkdocs]     sys.exit(load_entry_point('mkdocs==1.2.2', 'console_scripts', 'mkdocs')())
verbose: [mkdocs]   File "/usr/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
verbose: [mkdocs]     return self.main(*args, **kwargs)
verbose: [mkdocs]   File "/usr/lib/python3.9/site-packages/click/core.py", line 1062, in main
verbose: [mkdocs]     rv = self.invoke(ctx)
verbose: [mkdocs]   File "/usr/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
verbose: [mkdocs]     return _process_result(sub_ctx.command.invoke(sub_ctx))
verbose: [mkdocs]   File "/usr/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
verbose: [mkdocs]     return ctx.invoke(self.callback, **ctx.params)
verbose: [mkdocs]   File "/usr/lib/python3.9/site-packages/click/core.py", line 763, in invoke
verbose: [mkdocs]     return __callback(*args, **kwargs)
verbose: [mkdocs]   File "/usr/lib/python3.9/site-packages/mkdocs/__main__.py", line 173, in serve_command
verbose: [mkdocs]     serve.serve(dev_addr=dev_addr, livereload=livereload, **kwargs)
verbose: [mkdocs]   File "/usr/lib/python3.9/site-packages/mkdocs/commands/serve.py", line 78, in serve
verbose: [mkdocs]     server = config['plugins'].run_event('serve', server, config=config, builder=builder)
verbose: [mkdocs]   File "/usr/lib/python3.9/site-packages/mkdocs/plugins.py", line 94, in run_event
verbose: [mkdocs]     result = method(item, **kwargs)
verbose: [mkdocs]   File "/home/roman/.local/lib/python3.9/site-packages/mkdocs_monorepo_plugin/plugin.py", line 80, in on_serve
verbose: [mkdocs]     server.watch(self.originalDocsDir)
verbose: [mkdocs]   File "/usr/lib/python3.9/site-packages/mkdocs/livereload/__init__.py", line 68, in watch
verbose: [mkdocs]     path = os.path.abspath(path)
verbose: [mkdocs]   File "/usr/lib/python3.9/posixpath.py", line 374, in abspath
verbose: [mkdocs]     path = os.fspath(path)
verbose: [mkdocs] TypeError: expected str, bytes or os.PathLike object, not NoneType
```

Versions:
* techdocs-cli 0.7.0
* mkdocs 1.2.2
* mkdocs-techdocs-core 0.1.2

on Arch linux

Thanks

**Comment by camilaibs** [comment]
Starting to look at it 👀

**Comment by iamEAP** [comment]
Hey @RmMsr!  Just to confirm: does your `mkdocs.yml` file contain a `nav:` key?

**Comment by julioz** [comment]
@iamEAP Hi Eric, we've seeing the same in one of our repositories. If that helps, this is the complete `mkdocs.yml`:
```
site_name: Eng-Doc
site_url: <url>
repo_url: <url>
edit_uri: edit/master/content/

docs_dir: content

plugins:
  - techdocs-core

extra_css:
- colors.css

markdown_extensions:
- admonition:
- codehilite:
    guess_lang: false
- toc:
    permalink: true
- meta:
- pymdownx.superfences:
- pymdownx.tilde

theme:
  name: null
  custom_dir: mkdocs-material/material
  language: en
  logo: 'assets/images/logo.svg'
  icon: "\uE80C"
  palette:
    primary: orange
    accent: deep-purple
  font:
    text: Roboto
    code: Roboto Mono
  features: []
  static_templates:
    - 404.html
  include_search_page: false
  search_index_only: true
```
