### ISSUE TITLE
[QUESTION] How to pass config options to plantuml_markdown ?

### ISSUE THREAD

**Issue by vitteloil** [backstage/mkdocs-techdocs-core#94]
Hi,

I would like to use the plantuml feature supported by plantuml_markdown. If you check the plantuml_markdown code, it's looking for a "server" configuration entry. Not sure where to set this from within mkdocs ?

Thanks !

**Comment by MaeIsBad** [comment]
This is more of a mkdocs question, plantuml_markdown is an extension so you can configure it like so
```
site_name: 'asdf'
repo_name: 'GitHub'
remote_branch: 'master'

plugins:
  - techdocs-core

markdown_extensions:
  - plantuml_markdown:
      server: "http://example.com"
```

I don't think there is a way to configure mkdocs extension globaly
